version: '3'
services:
    sqlserver:
        image: microsoft/mssql-server-linux
        restart: always
        ports:
            - 1433:1433
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password12!
# Run
# docker-compose -f linux-mssqlserver.yml up -d 
# and connect to localhost with user sa and the specified password
