package pojos;

// default package
// Generated 9 mar. 2021 14:17:25 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Division generated by hbm2java
 */
@Entity
@Table(name = "division", catalog = "futbolsala", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Division extends Pojo implements java.io.Serializable  {

	private Integer id;
	private String nombre;
	private int numeroEquipos;
	private int numeroAscensos;
	private int numeroDescensos;
	private Set<Equipo> equipos = new HashSet<Equipo>(0);

	public Division() {
	}

	public Division(int numeroEquipos, int numeroAscensos, int numeroDescensos) {
		this.numeroEquipos = numeroEquipos;
		this.numeroAscensos = numeroAscensos;
		this.numeroDescensos = numeroDescensos;
	}

	public Division(String nombre, int numeroEquipos, int numeroAscensos, int numeroDescensos, Set<Equipo> equipos) {
		this.nombre = nombre;
		this.numeroEquipos = numeroEquipos;
		this.numeroAscensos = numeroAscensos;
		this.numeroDescensos = numeroDescensos;
		this.equipos = equipos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", unique = true, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "numeroEquipos", nullable = false)
	public int getNumeroEquipos() {
		return this.numeroEquipos;
	}

	public void setNumeroEquipos(int numeroEquipos) {
		this.numeroEquipos = numeroEquipos;
	}

	@Column(name = "numeroAscensos", nullable = false)
	public int getNumeroAscensos() {
		return this.numeroAscensos;
	}

	public void setNumeroAscensos(int numeroAscensos) {
		this.numeroAscensos = numeroAscensos;
	}

	@Column(name = "numeroDescensos", nullable = false)
	public int getNumeroDescensos() {
		return this.numeroDescensos;
	}

	public void setNumeroDescensos(int numeroDescensos) {
		this.numeroDescensos = numeroDescensos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "division")
	public Set<Equipo> getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Set<Equipo> equipos) {
		this.equipos = equipos;
	}

}
