package pojos;

// default package
// Generated 9 mar. 2021 14:17:25 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Equipo generated by hbm2java
 */
@Entity
@Table(name = "equipo", catalog = "futbolsala", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Equipo extends Pojo implements java.io.Serializable {

	private Integer nregistro;
	private Date timestamp;
	private Division division;
	private String nombre;
	private int puntos;
	private String pais;
	private Set<Jugador> jugadors = new HashSet<Jugador>(0);
	private Set<Patrocinador> patrocinadors = new HashSet<Patrocinador>(0);

	public Equipo() {
	}

	public Equipo(int puntos) {
		this.puntos = puntos;
	}

	public Equipo(Division division, String nombre, int puntos, String pais, Set<Jugador> jugadors,
			Set<Patrocinador> patrocinadors) {
		this.division = division;
		this.nombre = nombre;
		this.puntos = puntos;
		this.pais = pais;
		this.jugadors = jugadors;
		this.patrocinadors = patrocinadors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "nRegistro", unique = true, nullable = false)
	public Integer getNregistro() {
		return this.nregistro;
	}

	public void setNregistro(Integer nregistro) {
		this.nregistro = nregistro;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "timestamp", length = 10)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "division")
	public Division getDivision() {
		return this.division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	@Column(name = "nombre", unique = true, length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "puntos", nullable = false)
	public int getPuntos() {
		return this.puntos;
	}

	public void setPuntos(int puntos) {
		this.puntos = puntos;
	}

	@Column(name = "pais", length = 50)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipo")
	public Set<Jugador> getJugadors() {
		return this.jugadors;
	}

	public void setJugadors(Set<Jugador> jugadors) {
		this.jugadors = jugadors;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "equipopatrocinador", catalog = "futbolsala", joinColumns = {
			@JoinColumn(name = "equipo", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "patrocinador", nullable = false, updatable = false) })
	public Set<Patrocinador> getPatrocinadors() {
		return this.patrocinadors;
	}

	public void setPatrocinadors(Set<Patrocinador> patrocinadors) {
		this.patrocinadors = patrocinadors;
	}

}
