package pojos;

// default package
// Generated 9 mar. 2021 14:17:25 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Jugador generated by hbm2java
 */
@Entity
@Table(name = "jugador", catalog = "futbolsala", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Jugador extends Pojo implements java.io.Serializable {

	private Integer nregistro;
	private Equipo equipo;
	private String nombre;
	private Date fnacimiento;
	private float peso;

	public Jugador() {
	}

	public Jugador(float peso) {
		this.peso = peso;
	}

	public Jugador(Equipo equipo, String nombre, Date fnacimiento, float peso) {
		this.equipo = equipo;
		this.nombre = nombre;
		this.fnacimiento = fnacimiento;
		this.peso = peso;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "nRegistro", unique = true, nullable = false)
	public Integer getNregistro() {
		return this.nregistro;
	}

	public void setNregistro(Integer nregistro) {
		this.nregistro = nregistro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipo")
	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	@Column(name = "nombre", unique = true, length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fNacimiento", length = 10)
	public Date getFnacimiento() {
		return this.fnacimiento;
	}

	public void setFnacimiento(Date fnacimiento) {
		this.fnacimiento = fnacimiento;
	}

	@Column(name = "peso", nullable = false, precision = 12, scale = 0)
	public float getPeso() {
		return this.peso;
	}

	public void setPeso(float peso) {
		this.peso = peso;
	}

}
