package pojos;

// default package
// Generated 9 mar. 2021 14:17:25 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Patrocinador generated by hbm2java
 */
@Entity
@Table(name = "patrocinador", catalog = "futbolsala")
public class Patrocinador extends Pojo implements java.io.Serializable {

	private String nombre;
	private Integer presupuesto;
	private Set<Equipo> equipos = new HashSet<Equipo>(0);

	public Patrocinador() {
	}

	public Patrocinador(String nombre) {
		this.nombre = nombre;
	}

	public Patrocinador(String nombre, Integer presupuesto, Set<Equipo> equipos) {
		this.nombre = nombre;
		this.presupuesto = presupuesto;
		this.equipos = equipos;
	}

	@Id

	@Column(name = "nombre", unique = true, nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "presupuesto")
	public Integer getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(Integer presupuesto) {
		this.presupuesto = presupuesto;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "equipopatrocinador", catalog = "futbolsala", joinColumns = {
			@JoinColumn(name = "patrocinador", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "equipo", nullable = false, updatable = false) })
	public Set<Equipo> getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Set<Equipo> equipos) {
		this.equipos = equipos;
	}

}
